# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2021-03-22 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 21, 20, 34, 33, 844230)),
        ),
    ]
