# Generated by Django 3.1.7 on 2021-04-04 23:54

import datetime

from django.db import migrations

def datetime_to_date(apps, schema_editor):
    """Convert datetimes to dates"""
    Menu = apps.get_model('menu', 'Menu')
    Item = apps.get_model('menu', 'Item')
    for menu in Menu.objects.all():
        menu.created_date = menu.created_datetime.date()
        menu.expiration_date = menu.expiration_datetime.date()
        menu.save()
    for item in Item.objects.all():
        item.created_date = item.created_datetime.date()
        item.save()



class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210404_2146'),
    ]

    operations = [
        migrations.RunPython(datetime_to_date),
    ]
