# Generated by Django 3.1.7 on 2021-04-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_datetimes_to_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_datetime',
        ),
    ]
